# Generated by Django 3.0.5 on 2020-05-23 07:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20200517_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='worktrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Work_details', models.CharField(blank=True, max_length=200, null=True)),
                ('Total_Amount', models.IntegerField(max_length=50)),
                ('Amount_Paid', models.IntegerField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Assigned', models.CharField(max_length=50)),
                ('Target_Date', models.DateField(blank=True, null=True)),
                ('Comments', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update_date', models.DateField(default=datetime.date.today)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('unit', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
