# Generated by Django 3.0.5 on 2020-05-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200523_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktrack',
            name='Assigned',
        ),
        migrations.RemoveField(
            model_name='worktrack',
            name='id',
        ),
        migrations.AddField(
            model_name='worktrack',
            name='Assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worktrack',
            name='Sno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worktrack',
            name='Amount_Paid',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worktrack',
            name='Status',
            field=models.CharField(default='Working', max_length=50),
        ),
        migrations.AlterField(
            model_name='worktrack',
            name='Target_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='worktrack',
            name='Total_Amount',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worktrack',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
