# Generated by Django 3.0.5 on 2020-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200524_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktrack',
            old_name='Assigned_to',
            new_name='Payment_Status',
        ),
        migrations.RenameField(
            model_name='worktrack',
            old_name='Status',
            new_name='Work_Status',
        ),
        migrations.AddField(
            model_name='worktrack',
            name='Mobile',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
