# Generated by Django 3.0.5 on 2020-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200524_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktrack',
            name='Mobile',
            field=models.IntegerField(default=91, max_length=15),
        ),
    ]
