# Generated by Django 3.0.5 on 2020-07-14 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_auto_20200524_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='marriage',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Surname', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Skin_tone', models.CharField(blank=True, max_length=20, null=True)),
                ('Study', models.CharField(blank=True, max_length=100, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Contact_number', models.IntegerField(default=91, max_length=15)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
