# Generated by Django 3.0.5 on 2020-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200714_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='image',
            field=models.ImageField(blank=True, upload_to='marriage_image'),
        ),
    ]
