# Generated by Django 3.1.3 on 2021-05-21 16:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_auto_20210204_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='IC_Expensive',
            fields=[
                ('S_no', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Item_amount', models.IntegerField(blank=True, null=True)),
                ('date_purchase', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IC_Product',
            fields=[
                ('Product_no', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Market_price', models.FloatField(blank=True, null=True)),
                ('Whole_sal_price', models.FloatField(blank=True, null=True)),
                ('No_items_in_box', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IC_Stock_purchased',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date_purchase', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ic_product', verbose_name='Product_name')),
            ],
        ),
        migrations.CreateModel(
            name='IC_Stock_sold',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date_sold', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ic_product', verbose_name='Product_name')),
            ],
        ),

    ]
